### ISSUE TITLE
[REQUEST] Use dynamic or customizable memory and disk size

### ISSUE THREAD

**Issue by sam-baird** [CDPHE-bioinformatics/CDPHE-SARS-CoV-2#37] opened 2024-08-29 21:38 UTC
### Feature Request
Currently we hard-code values for disk size and memory which requires branching and changing the underlying code when tasks fail due to insufficient disk space or memory. 

### Solution
There are many tools used in our workflows whose memory/disk requirements scale significantly with the size of the inputs like (ivar, seqyclean, samtools, bwa). For tasks using these tools, we should use `maxRetries` for scaling memory and [dynamic disk size](https://terra.bio/reduce-computing-costs-by-tailoring-resource-allocations-in-workflows/) for scaling disk size. It may be a good idea to also expose memory and disk size as input variables.

### Upstream effects
We should set a memory factor default on Terra that is reasonable (otherwise we can end up requesting way too much memory).

### Downstream effects
None

**Comment by danpolanco** [comment] 2024-09-04 16:43
Closing as duplicate of #10.

**Closed by danpolanco** 2024-09-04 16:43 UTC
